config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :installs
  
  resources :posts, only: [:index, :show, :new, :create, :edit, :update]

  root 'main#home'

  get 'my_account', to: 'users#my_account'
  
  post '/posts', to: 'posts#create'  
  
  resources :posts do
    member do
      post 'upvote'
      get 'edit'
      patch 'update'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  attribute :upvote_count, :integer, default: 0

  def self.ransackable_attributes(auth_object = nil)
    ["contents", "created_at", "id", "subject", "updated_at", "upvote_count", "user_id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @q = Post.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?  # Set default to newest first.
    @posts = @q.result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def edit
    @post = Post.find(params[:id])
  end

  def create
    Rails.logger.info("Received parameters: #{params.inspect}")
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        flash[:notice] = "Post was successfully created."
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        flash[:alert] = "Failed to create the post"
        logger.error("Failed: #{@post.errors}")
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    Rails.logger.info("Update called")
    respond_to do |format|
      @post = Post.find(params[:id])
      if @post.update(post_params)
        format.html { redirect_to my_account_path, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post was successfully deleted."
    respond_to do |format|
      format.html { redirect_to my_account_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.increment!(:upvote_count)
    redirect_to root_path
  end


  private
    def set_post
      @post = Post.find(params[:id])
    end

    # Params for post request.
    def post_params
      params.require(:post).permit(:subject, :contents).merge(user_id: current_user.id)
    end
    
    
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_account
    @user = current_user
    @posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def extract_username_from_email(email)
    match = email.match(/^([^@]+)@/)
    # From beginning of string - capture one or more characters that are not @ - Ensure there is an @ symbol
    match[1] if match
    # Match [1] instead of match[0] excludes the "@" symbol.
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-100">
  <div class="container mx-auto">
    <div class="flex justify-between items-center px-4 sm:px-0">
      <a class="w-1/4 my-2" href="/"><%= image_tag "well-giving-logo.png", class:"h-12 w-16 sm:h-full sm:w-2/5"%></a>
      <ul class="flex space-x-4 items-center">
        <% if current_user %>
        <li class="text-sm md:text-base">
          <% if controller_name == 'users' && action_name == 'my_account' %>
            <%= link_to "Edit Account", edit_user_registration_path, class: "sm:px-4 sm:py-2 py-1 px-2  text-white bg-blue-500 hover:bg-blue-700 rounded" %>
          <% else %>
            <%= link_to "My Account", my_account_path, class: "sm:px-4 sm:py-2 py-1 px-2  text-white bg-blue-500 hover:bg-blue-700 rounded" %>
          <% end %>
            
          </li>
          <li class="text-sm md:text-base">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "sm:px-4 sm:py-2 py-1 px-2 text-white bg-orange-500 hover:bg-orange-700  rounded" %>
          </li>
        <% else %>
        <li class="text-sm md:text-base">
          <%= link_to "Log In", new_user_session_path, class: "sm:px-4 sm:py-2 py-1 px-2  text-white bg-blue-500 hover:bg-blue-700 rounded" %>
        </li>
        <li class="text-sm md:text-base">
            <%= link_to "Sign Up", new_user_registration_path, class: "sm:px-4 sm:py-2 py-1 px-2  text-white bg-orange-500 hover:bg-orange-700  rounded" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WellGivingBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% if flash[:notice] %>
      <div class="bg-green-100 border-l-4 border-green-500 text-green-800 p-4 relative" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="absolute top-0 bottom-0 right-0 px-4 py-3" data-dismiss="alert" aria-label="Close">
          <svg class="h-6 w-6 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-800 p-4 relative" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="absolute top-0 bottom-0 right-0 px-4 py-3" data-dismiss="alert" aria-label="Close">
          <svg class="h-6 w-6 text-yellow-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
    <% end %>

    <div class = "text-center flex flex-col items-center">
     <%= yield %>
    </div>
  </body>
</html>

app/views/main/home.html.erb
<% if current_user %>
<h1 class="text-xl sm:text-2xl lg:text-4xl my-4 p-1 border border-gray-100 rounded w-4/5 md:w-2/5">Hello, <%= extract_username_from_email(current_user.email)%>. Welcome to our blog!</h1>
<% else %>
<h1 class="text-xl sm:text-2xl lg:text-4xl my-4 p-1 border border-gray-100 rounded w-2/5">Welcome to Our Blog!</h1>
<% end %>

<div class="container w-full h-fit flex flex-wrap flex-col items-center justify-self-center">
<% if user_signed_in? %>
<%= render "posts/form", post: @post %>
<% else %>
<h1 class="text-xl my-4 border-b border-gray-100">Please sign in to post.</h1>
<% end %>  
<%= render "posts/index"%>

  </section>
</div>

app/views/posts/_editform.html.erb
<main class="w-4/5 flex flex-col items-center">
<h1 class="text-xl sm:text-2xl lg:text-4xl w-full border border-gray-100 rounded p-1 my-4">Edit Post:</h1>
<form class="w-full lg:w-2/5 border border-gray-100 rounded flex flex-col items-center p-4 my-4 sm:text-base text-sm" method="patch" action="<%= post_path(@post) %>" enctype="multipart/form-data">
  <%= form_with(model: @post, local: true) do |form| %>

    <div class="field flex flex-col w-4/5 lg:w-3/5 items-start my-1">
      <%= form.label :subject, "Topic:" %>
      <%= form.text_field :subject, id: "post_subject", name: "post[subject]", class: "w-full border rounded p-1 ", required: true, minlength: 5 %>
    </div>

    <div class="ield flex flex-col w-4/5 lg:w-3/5 items-start my-1">
      <%= form.label :contents, "Description:" %>
      <%= form.text_area :contents, id: "post_contents", name: "post[contents]", class: "w-full border rounded p-1", required: true, minlength: 5 %>
    </div>

    <div class="actions w-3/5 md:w-2/5 items-start py-2 my-1">
      <%= form.submit "Submit", class:"w-full cursor-pointer text-white bg-blue-500 hover:bg-blue-700 rounded p-1"%>
    </div>
    <% end %>
    </form>
</main>

app/views/posts/_form.html.erb
<h1 class="text-md md:text-xl my-4 border-b border-gray-100 p-4">Tell us what you have achieved or how you feel today:</h1>
<form class="w-4/5 md:w-2/5 border border-gray-100 rounded flex flex-col items-center p-4 sm:text-base text-sm" method="post" action="<%= posts_path %>">
  <%= form_with(model: @post, url: posts_path, method: :post) do |form| %>
    <div class="field flex flex-col w-4/5 lg:w-3/5 items-start my-1">
      <%= form.label :subject, "Topic:" %>
      <%= form.text_field :subject, id: "post_subject", name: "post[subject]", class: "w-full border rounded p-1", required: true, minlength: 5 %>
    </div>

    <div class="field flex flex-col w-4/5 lg:w-3/5 items-start my-1">
      <%= form.label :contents, "Description:" %>
      <%= form.text_area :contents, id: "post_contents", name: "post[contents]", class: "w-full border rounded p-1", required: true, minlength: 20 %>
    </div>

    <div class="actions w-3/5 md:w-2/5 items-start py-2 my-1">
      <%= form.submit "Submit", class:"w-full cursor-pointer text-white bg-blue-500 hover:bg-blue-700 rounded p-1"%>
    </div>
  <% end %>
</form>

app/views/posts/_index.html.erb
<div class = "flex md:flex-row md:w-2/5 md:items-center md:justify-center flex-col w-4/5 justify-center items-center sm:text-base text-sm">
  <%= render "/posts/sortfilter" %>
  <%= search_form_for @q,class:"flex flex-col w-2/5 px-4" ,url: "" do |f| %>
    <div class="form-group my-4 flex flex-col items-center md:items-start">
      <%= f.label :contents_cont, "Search Posts:"%>
      <section class="flex flex-col items-center md:items-start">
        <%= f.text_field :contents_cont, :class => "form-control border border-gray-100 rounded pl-2 py-2 my-2", :placeholder => "Enter a few characters" %>
      <div>
        <%= f.submit :class => "cursor-pointer px-4 py-2 text-white bg-blue-500 hover:bg-blue-700 rounded" %>
        <%= link_to "Clear", root_path, class: "btn btn-default btn-block px-4 py-2 bg-gray-100 rounded"%> 
      </div>
      </section>
    </div>
<% end %>
</div>

<h2 class=" sm:text-md lg:text-xl my-4 p-1 border border-gray-100 rounded w-4/5 md:w-2/5">Here are some of our latest entries:</h2>
<section class="w-4/5 h-auto py-10 flex flex-wrap justify-center lg:justify-between sm:text-base text-sm">
<% @posts.each do |post| %>
  <div class="blog-post w-4/5 lg:w-2/5 border border-gray-100 rounded flex flex-col items-center p-4 my-4">
    <div class="field flex flex-col w-4/5 md:w-3/5 items-start">
      <h2 class="p-1 border-b border-gray-100">Title:</h2>
      <p class="w-full border rounded p-1">
        <%= post.subject %>
      </p>
    </div>

    <div class="field flex flex-col w-4/5 md:w-3/5 items-start">
      <h2 class="p-1 border-b border-gray-100">Contents:</h2>
      <p class="w-full border rounded p-1">
        <%= post.contents %>
      </p>
    </div>

    <div class="field w-full px-4 flex flex-col items-center justify-center md:flex-row md:items-between md:justify-center">
       <div class="field flex-col items-center justify-center sm:flex-row sm:items-between sm:justify-center w-3/5">
        <h2 class="p-1 ">Posted by:</h2>
        <%= extract_username_from_email(post.user.email) %>
      </div>
      <div class="flex flex-col items-center justify-between md:flex-row md:w-4/5 md:items-between md:justify-center">
      <%= button_to upvote_post_path(post), method: :post, class: 'upvote-button my-2 p-1 flex w-full h-full flex-row items-center justify-end' do %>
        <%= image_tag "clapping.png", class: "md:w-12 md:h-12 w-8 h-8" %>
        <p class="mt-1"><%= post.upvote_count %></p>
      <% end %>      
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_sortfilter.html.erb
<div class="sorting-options px-4 mt-4 sm:text-base text-sm">
  <%= form_tag(root_path, method: :get, class: 'form-inline flex flex-col items-center md:items-start') do %>
    <label for="q_s">Sort by:</label>
    <%= select_tag 'q[s]',options_for_select([['Newest', 'created_at desc'], ['Oldest', 'created_at asc'], ['Highest Votes', 'upvote_count desc'], ['Lowest Votes', 'upvote_count asc']], params[:q]&.dig(:s)), class: 'form-control border border-gray-100 rounded pl-2 py-2 my-2' %>
    <%= submit_tag 'Apply', class: 'cursor-pointer px-4 py-2 text-white bg-blue-500 hover:bg-blue-700 rounded' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "editform", post: @post %>
<%= link_to "Cancel", my_account_path, class:"px-4 py-2 text-white bg-gray-200 hover:bg-gray-300  rounded text-black" %>

app/views/users/my_account.html.erb
<main class="flex flex-col items-center w-full">
<h1 class="text-xl sm:text-2xl lg:text-4xl my-4 p-1 border border-gray-100 rounded w-2/5">Welcome, <%= extract_username_from_email(current_user.email) %>!</h1>

<h2 class="text-2xl border-b border-gray-100 mb-4">Here are your posts:</h2>
<div class="w-4/5 h-auto py-10 flex flex-wrap justify-center lg:justify-between sm:text-base text-sm">
  <% @posts.each do |post| %>
    <div class="blog-post w-4/5 lg:w-2/5 border border-gray-100 rounded flex flex-col items-center p-4 my-4">
      <div class="field flex flex-col w-4/5 md:w-3/5 items-start">
        <h2 class="p-1 border-b border-gray-100">Title:</h2>
        <p class="w-full border rounded p-1">
          <%= post.subject %>
        </p>
      </div>
      <div class="field flex flex-col w-4/5 md:w-3/5 items-start">
      <h2 class="p-1 border-b border-gray-100">Contents:</h2>
      <p class="w-full border rounded p-1">
        <%= post.contents %>
      </p>
      </div>
      <div class="field w-full px-4 flex flex-col items-center justify-center md:flex-row md:items-between md:justify-center">
      <div class="field flex-col items-center justify-center sm:flex-row sm:items-between sm:justify-center w-3/5">
       <h2 class="p-1">Posted by:</h2>
         <%= extract_username_from_email(post.user.email) %>
     </div>
     <div class="flex flex-col items-center justify-between md:flex-row md:w-4/5 md:items-between md:justify-center">
     <div class='upvote-button my-2 p-1 flex w-full h-full flex-row items-center justify-end'>
       <%= image_tag "clapping.png", class: "md:w-12 md:h-12 w-8 h-8" %>
       <p class="mt-1"><%= post.upvote_count %></p>
     </div>     
     </div>
   </div>
        <%= link_to 'Edit', edit_post_path(post), method: :patch, class:"px-12 py-2 text-white bg-blue-500 hover:bg-blue-700  rounded my-4" %>
        <%= form_for post, url: post_path(post), method: :delete, id:"delete_post", data: { confirm: "Are you sure you want to delete this post?" } do |f| %>
        <%= f.submit "Delete Post", class: "cursor-pointer", data: {turbo_confirm: "Are you sure you want to delete this post? All of your posts will also be deleted." }, class: "px-4 py-2 text-white bg-red-500 hover:bg-red-700  rounded" %>
     </div>
    <% end %>
    <% end %>
  </div>
</main>
</body>
</html>